#!/usr/bin/env python3
"""App 的界面文案（中英）。改这里再跑 `python3 tool/strings.py` 生成 lib/l10n/app_zh.arb、app_en.arb。
占位符写成 {name}；数字占位符在 INT 里列出。"""
import json, re, pathlib

INT = {"count", "ok", "failed", "days", "level", "supported", "ms", "inLibrary", "aired"}

S = [
    ("appTitle", "pt-tools", "pt-tools"),
    ("retry", "重试", "Retry"),
    ("cancel", "取消", "Cancel"),
    ("paste", "粘贴", "Paste"),
    ("actions", "操作", "Actions"),
    ("empty", "没有内容", "Nothing here"),
    ("errorPrefix", "出错了：{message}", "Something went wrong: {message}"),
    ("navOverview", "概览", "Overview"),
    ("navTorrents", "种子", "Torrents"),
    ("navSearch", "搜索", "Search"),
    ("navMedia", "媒体", "Media"),
    ("navMore", "更多", "More"),
    ("connConnecting", "正在连接…", "Connecting…"),
    ("connOnline", "已连上", "Connected"),
    ("connFailed", "连不上：{message}", "Can't connect: {message}"),
    ("connRevoked", "这台设备被撤销了，请重新配对", "This device was revoked. Pair it again."),
    ("connKeyRotated", "主机的密钥换了，请重新配对", "The host's keys changed. Pair this device again."),
    ("connDisabled", "主机关掉了远程访问", "Remote access is turned off on the host"),
    ("connOffline", "未连接", "Not connected"),
    ("repair", "重新配对", "Pair again"),
    ("viaDirect", "直连", "Direct"),
    ("viaRelay", "relay", "Relay"),
    ("pairTitle", "配对 pt-tools", "Pair with pt-tools"),
    ("pairIntro", "在 pt-tools 网页上打开「系统 → 远程访问 → 添加设备」，扫二维码，或者把链接粘贴到下面。", "In pt-tools, open System → Remote access → Add device, then scan the QR code or paste the link below."),
    ("pairScan", "扫码", "Scan QR code"),
    ("pairLinkLabel", "配对链接", "Pairing link"),
    ("pairNameLabel", "设备名", "Device name"),
    ("pairNameDefault", "我的手机", "My phone"),
    ("pairButton", "配对", "Pair"),
    ("pairWorking", "正在配对…", "Pairing…"),
    ("pairInvalidLink", "链接不对：{message}", "That link isn't valid: {message}"),
    ("pairUpgrade", "这个配对链接要更新版本的 App", "This pairing link needs a newer version of the app"),
    ("pairPrivacy", "连接是端到端加密的：经 relay 时 relay 只转发，看不到内容。这台设备的私钥只存在手机上。", "Connections are end-to-end encrypted: a relay only forwards traffic and cannot read it. This device's private key never leaves the phone."),
    ("scanTitle", "扫描配对二维码", "Scan the pairing QR code"),
    ("scanUnavailable", "这台设备不能扫码，请返回粘贴链接", "Scanning isn't available on this device. Go back and paste the link."),
    ("hostVersion", "pt-tools {version}", "pt-tools {version}"),
    ("apiLevelMismatch", "主机的 App API 级别是 {level}，这个 App 认得 {supported}，请升级", "The host uses App API level {level}; this app supports {supported}. Please update."),
    ("kpiUploaded", "上传", "Uploaded"),
    ("kpiDownloaded", "下载", "Downloaded"),
    ("kpiRatio", "分享率", "Ratio"),
    ("kpiBonus", "魔力", "Bonus"),
    ("perHour", "每小时 {value}", "{value} per hour"),
    ("kpiSeeding", "做种", "Seeding"),
    ("kpiUnread", "站内信未读", "Unread messages"),
    ("siteCount", "{count} 个站点", "{count} sites"),
    ("todayTitle", "今天", "Today"),
    ("todayError", "今天的增量算不出来：{message}", "Today's numbers aren't available: {message}"),
    ("todayBySite", "各站点", "By site"),
    ("downloadersTitle", "下载器", "Downloaders"),
    ("downloaderUnreachable", "连不上", "Unreachable"),
    ("freeSpace", "剩余 {size}", "{size} free"),
    ("updatedAt", "站点数据更新于 {time}", "Site data updated {time}"),
    ("torrentsAll", "全部", "All"),
    ("stateDownloading", "下载中", "Downloading"),
    ("stateSeeding", "做种中", "Seeding"),
    ("statePaused", "已暂停", "Paused"),
    ("stateStopped", "已停止", "Stopped"),
    ("stateQueued", "排队中", "Queued"),
    ("stateChecking", "校验中", "Checking"),
    ("stateError", "出错", "Error"),
    ("searchTorrentsHint", "按标题筛选", "Filter by title"),
    ("noTorrents", "下载器里没有种子", "No torrents in your downloaders"),
    ("actionPause", "暂停", "Pause"),
    ("actionResume", "继续", "Resume"),
    ("actionDelete", "删除", "Delete"),
    ("deleteTitle", "删除这个种子？", "Delete this torrent?"),
    ("deleteWithFiles", "连同已下载的数据一起删除", "Also delete downloaded data"),
    ("actionDone", "成功 {ok} 个，失败 {failed} 个", "{ok} succeeded, {failed} failed"),
    ("torrentFailures", "有 {count} 个下载器没有读到，列表不完整", "{count} downloader(s) couldn't be read; the list is incomplete"),
    ("etaLabel", "剩余 {eta}", "ETA {eta}"),
    ("searchHint", "搜索站点上的种子", "Search torrents on your sites"),
    ("searchIntro", "输入关键字，在所有启用的站点上一起搜", "Type a keyword to search all enabled sites at once"),
    ("searchFreeOnly", "只看免费", "Free only"),
    ("searchNoResults", "没有找到", "No results"),
    ("searchSites", "{count} 个站点 · {ms} ms", "{count} sites · {ms} ms"),
    ("searchErrors", "{count} 个站点出错", "{count} site(s) failed"),
    ("pushTitle", "推送到下载器", "Send to downloader"),
    ("pushDefault", "默认下载器", "Default downloader"),
    ("pushOk", "已推送到 {downloader}", "Sent to {downloader}"),
    ("pushSkipped", "下载器里已经有这个种子", "The downloader already has this torrent"),
    ("pushBlocked", "没有推送：{message}", "Not sent: {message}"),
    ("defaultBadge", "默认", "Default"),
    ("free", "免费", "Free"),
    ("hr", "H&R", "H&R"),
    ("tabSubscriptions", "订阅", "Subscriptions"),
    ("tabHistory", "最近入库", "Recently added"),
    ("tabExplore", "探索", "Explore"),
    ("noSubscriptions", "没有订阅；可以在「探索」里订阅", "No subscriptions yet; subscribe from Explore"),
    ("noHistory", "没有整理记录", "Nothing organized yet"),
    ("subActive", "订阅中", "Active"),
    ("subPaused", "已暂停", "Paused"),
    ("subPending", "等待中", "Pending"),
    ("subDone", "已完成", "Done"),
    ("subUpgrade", "洗版", "Upgrade"),
    ("subProgress", "已入库 {inLibrary}/{aired} 集", "{inLibrary}/{aired} episodes in library"),
    ("subMissing", "缺 {list}", "Missing {list}"),
    ("subPause", "暂停订阅", "Pause"),
    ("subResume", "恢复订阅", "Resume"),
    ("subSearchNow", "立即搜索", "Search now"),
    ("subDelete", "删除订阅", "Delete subscription"),
    ("subDeleteConfirm", "删除这个订阅？下载器里的种子与媒体库里的文件不动。", "Delete this subscription? Torrents in your downloaders and files in your library are kept."),
    ("subNextSearch", "下次搜索 {time}", "Next search {time}"),
    ("episodesTitle", "剧集", "Episodes"),
    ("epLibrary", "已入库", "In library"),
    ("epDownloading", "下载中", "Downloading"),
    ("epMissing", "缺", "Missing"),
    ("epUpcoming", "未播出", "Not aired"),
    ("subTorrentsTitle", "下载过的种子", "Downloaded torrents"),
    ("exploreMovie", "电影", "Movies"),
    ("exploreTv", "剧集", "TV"),
    ("exploreTrending", "热门", "Trending"),
    ("explorePopular", "流行", "Popular"),
    ("exploreSearchHint", "搜索电影或剧集", "Search movies or TV"),
    ("subscribe", "订阅", "Subscribe"),
    ("subscribed", "已订阅", "Subscribed"),
    ("inLibrary", "已入库", "In library"),
    ("subscribeOk", "已订阅 {title}", "Subscribed to {title}"),
    ("moreSites", "站点", "Sites"),
    ("moreTasks", "任务", "Tasks"),
    ("moreBrush", "刷流", "Brush"),
    ("moreDownloaders", "下载器", "Downloaders"),
    ("moreSettings", "连接与设备", "Connection & device"),
    ("siteDisabled", "未启用", "Disabled"),
    ("disabledSites", "未启用的站点（{count}）", "Disabled sites ({count})"),
    ("noEnabledSites", "没有启用的站点", "No sites enabled"),
    ("movieNotInLibrary", "未入库", "Not in library"),
    ("loginDays", "离封号还有 {days} 天", "{days} days before the inactivity limit"),
    ("loginUnknown", "没有访问记录", "No visit recorded"),
    ("attend", "签到", "Check in"),
    ("attendOk", "签到完成", "Checked in"),
    ("attendSigned", "今天已签到", "Checked in today"),
    ("attendFailed", "签到失败", "Check-in failed"),
    ("attendPending", "今天未签到", "Not checked in today"),
    ("attendUnsupported", "不支持签到", "Check-in not supported"),
    ("unreadMessages", "{count} 条未读", "{count} unread"),
    ("siteUserError", "站点上的用户数据没读到：{message}", "Couldn't read user data from the sites: {message}"),
    ("noTasks", "没有推送记录", "No tasks yet"),
    ("taskPushed", "已推送", "Sent"),
    ("taskNotPushed", "未推送", "Not sent"),
    ("taskCompleted", "已完成", "Completed"),
    ("noBrush", "没有刷流任务", "No brush tasks"),
    ("brushDisabled", "已停用", "Disabled"),
    ("brushActive", "在刷 {count} 个", "{count} active"),
    ("brushToday", "今天 ↑{up} ↓{down}", "Today ↑{up} ↓{down}"),
    ("brushTotal", "累计 ↑{up} ↓{down}", "Total ↑{up} ↓{down}"),
    ("noDownloaders", "没有启用的下载器", "No downloaders enabled"),
    ("settingsConnection", "连接", "Connection"),
    ("settingsVia", "方式", "Via"),
    ("settingsEndpoint", "地址", "Address"),
    ("settingsHost", "主机", "Host"),
    ("settingsReconnect", "重新连接", "Reconnect"),
    ("settingsDevice", "这台设备", "This device"),
    ("settingsPairedAt", "配对于 {time}", "Paired {time}"),
    ("settingsScopes", "权限", "Permissions"),
    ("scopeFull", "完全控制", "Full control"),
    ("scopeRead", "只读", "Read-only"),
    ("settingsForget", "忘掉这台主机", "Forget this host"),
    ("forgetConfirm", "忘掉以后要重新扫码配对。主机上的设备记录不会删除，需要的话在网页上撤销。", "You'll need to scan again to pair. The device record stays on the host; revoke it in the web UI if needed."),
]

BANNED_ZH = ["还没", "没能", "免得", "搭的", "咋", "啥", "搞定", "折腾"]
BANNED_EN = [r"\bjust\b", r"\bgonna\b", r"\bstuff\b"]

def build():
    keys = [k for k, _, _ in S]
    assert len(keys) == len(set(keys)), "重复的键"
    zh, en = {"@@locale": "zh"}, {"@@locale": "en"}
    for k, z, e in S:
        for w in BANNED_ZH:
            assert w not in z, f"{k}: 中文里有「{w}」"
        for w in BANNED_EN:
            assert not re.search(w, e, re.I), f"{k}: English has {w}"
        pz, pe = re.findall(r"\{(\w+)\}", z), re.findall(r"\{(\w+)\}", e)
        assert sorted(pz) == sorted(pe), f"{k}: 占位符不一致 {pz} {pe}"
        zh[k], en[k] = z, e
        if pz:
            zh["@" + k] = {"placeholders": {p: {"type": "int" if p in INT else "String"} for p in dict.fromkeys(pz)}}
    here = pathlib.Path(__file__).resolve().parent.parent / "lib" / "l10n"
    here.mkdir(parents=True, exist_ok=True)
    (here / "app_zh.arb").write_text(json.dumps(zh, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    (here / "app_en.arb").write_text(json.dumps(en, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"{len(S)} 条文案")

if __name__ == "__main__":
    build()
