blank_issues_enabled: true
contact_links:
  - name: "Telegram 交流群"
    url: https://t.me/+7YK2kmWIX0s1Nzdl
    about: "加入 Telegram 群组交流讨论"
  - name: "QQ 群: 274984594"
    url: https://qm.qq.com/q/274984594
    about: "加入 QQ 群交流讨论"
